<a href="https://colab.research.google.com/github/zo-ff/pandas/blob/main/pd_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

# このデータフレーム（sensor_df）を使います！
sensor_df = pd.DataFrame({
    'temp': [22.5, 45.0, 18.2, 50.5],
    'press': [100, 150, 95, 210]
})
# 1. 判定用の関数を作る
def check_sensor(row):
    if row['temp']>=50 or row['press']>=200:
        return 1
    else:
        return 0

# 2. apply で適用する
sensor_df['error_flag'] = sensor_df.apply([check_sensor],axis=1)  #axis=0 縦方向に切り出し、インデックスの数字しか見えないため'temp'や'press'指定はエラー
sensor_df                                                         #axis=1　横方向に切り出しシリーズ化、逆にインデックスの数字は見えないため、カラム名指定

#Pandasの Series（1本の列）というデータ構造は、「値」と「インデックス」の2つしか持てない というケチな制約があります。
#そのため、切り出した瞬間に、どちらか片方の情報（行名か列名か）をインデックスとして採用し、もう片方は捨てざるを得ない、という大人の事情（仕様）からこの動きになっています。

   temp  press  error_flag
0  22.5    100           0
1  45.0    150           0
2  18.2     95           0
3  50.5    210           1

In [15]:
import pandas as pd

d={'items_name':['りんご', 'バナナ', 'オレンジ', 'メロン'],'price':[150, 100, 120, 800],'sold_count':[10, 25, 15, 3]}
df=pd.DataFrame(d)
translation_dict = {
    'りんご': 'Apple',
    'バナナ': 'Banana',
    'オレンジ': 'Orange',
    'メロン': 'Melon'
}
df['english_name']=df['items_name'].map(translation_dict)  #カラム一つに適用
mpr=df['price'].mean()
df['npr']=df['price'].map(lambda p: p-mpr)
df2=df[['price','sold_count']].apply(sum)  #すべてのカラムにSUM適用
df2

price         1170
sold_count      53
dtype: int64

In [ ]:
import pandas as pd

# 航空機の乗客数（月次データ）
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/flights.csv")
df[df['year']==1960]

     year      month  passengers
132  1960    January         417
133  1960   February         391
134  1960      March         419
135  1960      April         461
136  1960        May         472
137  1960       June         535
138  1960       July         622
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [ ]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset("taxis")
df['pickup']=pd.to_datetime(df['pickup'])
pd.DataFrame.sort_index?

In [ ]:
pd.to_datetime()
set_index()
sort_index()
sort_values()
reset_index()

In [ ]:
import pandas as pd
eiga=pd.read_csv('/content/eiga.csv')  #read_csvだけはリストでｃｓｖ（テキスト）を返してくる
eiga.head()

,Unnamed: 0,0,1,2,3,4,5
0,0,順位,公開月,作品名,興収 (単位： 億円),興収 (単位： 億円),配給会社
1,1,1,7,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,391.4,★,東宝/アニプレックス
2,2,2,6,国宝,195.5,★,東宝
3,3,3,4,名探偵コナン 隻眼の残像（フラッシュバック）,147.4,NaN,東宝
4,4,4,9,劇場版『チェンソーマン レゼ篇』,104.3,★,東宝

In [ ]:
import os
import pandas as pd

if os.path.exists('eiga.csv'):
  df=pd.read_csv('eiga.csv') # CSVあり
else:
  df=pd.read_html('https://www.eiren.org/toukei/index.html',match='鬼滅')
  df=df[0]
  df.to_csv('eiga.csv')

    # CSVなし

In [ ]:
# df = pd.read_csv('ykhm.csv', encoding="shift_jis",skiprows=[0,4,5],header=[0,1])
# df.head()

with open('ykhm.csv', encoding='shift_jis') as f:
    for i, line in enumerate(f):
        if i < 10:
            print(i, repr(line))

0 'ダウンロードした時刻：2026/05/24 10:46:16\n'
1 '\n'
2 ',横浜,横浜,横浜,横浜,横浜,横浜\n'
3 '年月日,最高気温(℃),最高気温(℃),最高気温(℃),最低気温(℃),最低気温(℃),最低気温(℃)\n'
4 ',,,,,,\n'
5 ',,品質情報,均質番号,,品質情報,均質番号\n'
6 '2021/5/23,24.9,8,1,15.4,8,1\n'
7 '2021/5/24,27.6,8,1,17.6,8,1\n'
8 '2021/5/25,28.3,5,1,17.2,5,1\n'
9 '2021/5/26,25.6,8,1,18.4,8,1\n'

In [ ]:
 import pandas as pd
 print(pd.DataFrame({'a':[1],'b':[2]},['x','y',111]))
print(pd.DataFrame([[1,2]],columns=('a','b')))

     a  b
x    1  2
y    1  2
111  1  2
   a  b
0  1  2